CREATE TABLE ACCOUNTS
(
    custid BIGINT      NOT NULL PRIMARY KEY,
    name   VARCHAR(64) NOT NULL
) ENGINE = InnoDB;

CREATE TABLE SAVINGS
(
    custid  BIGINT NOT NULL PRIMARY KEY,
    balance FLOAT  NOT NULL,
    FOREIGN KEY (custid) REFERENCES ACCOUNTS (custid)
) ENGINE = InnoDB;

CREATE TABLE CHECKING
(
    custid  BIGINT NOT NULL PRIMARY KEY,
    balance FLOAT  NOT NULL,
    FOREIGN KEY (custid) REFERENCES ACCOUNTS (custid)
) ENGINE = InnoDB;
