CREATE TABLE city (
ID INTEGER NOT NULL PRIMARY KEY,
Name CHAR(35) NOT NULL DEFAULT '',
CountryCode CHAR(3) NOT NULL DEFAULT '',
District CHAR(20) NOT NULL DEFAULT '',
Population INTEGER NOT NULL DEFAULT '0',
CONSTRAINT city_ibfk_1 FOREIGN KEY (CountryCode) REFERENCES country (Code)
);

CREATE TABLE country (
Code CHAR(3) NOT NULL DEFAULT '',
Name CHAR(52) NOT NULL DEFAULT '',
Continent TEXT NOT NULL DEFAULT 'Asia',
Region CHAR(26) NOT NULL DEFAULT '',
SurfaceArea FLOAT(10,2) NOT NULL DEFAULT '0.00',
IndepYear INTEGER DEFAULT NULL,
Population INTEGER NOT NULL DEFAULT '0',
LifeExpectancy FLOAT(3,1) DEFAULT NULL,
GNP FLOAT(10,2) DEFAULT NULL,
GNPOld FLOAT(10,2) DEFAULT NULL,
LocalName CHAR(45) NOT NULL DEFAULT '',
GovernmentForm CHAR(45) NOT NULL DEFAULT '',
HeadOfState CHAR(60) DEFAULT NULL,
Capital INTEGER DEFAULT NULL,
Code2 CHAR(2) NOT NULL DEFAULT '',
PRIMARY KEY (Code)
);

CREATE TABLE countrylanguage (
CountryCode CHAR(3) NOT NULL DEFAULT '',
Language CHAR(30) NOT NULL DEFAULT '',
IsOfficial TEXT NOT NULL DEFAULT 'F',
Percentage FLOAT(4,1) NOT NULL DEFAULT '0.0',
PRIMARY KEY (CountryCode,Language),
CONSTRAINT countryLanguage_ibfk_1 FOREIGN KEY (CountryCode) REFERENCES country (Code)
);

CREATE INDEX idx_countrylanguage_CountryCode ON countrylanguage (CountryCode);

CREATE INDEX idx_city_CountryCode ON city (CountryCode);